# build stage
FROM node:18-alpine as build-stage
WORKDIR /app

COPY packages ./packages
COPY package.json ./
COPY yarn.lock ./
COPY turbo.json ./
COPY apps/standalone ./apps/standalone

RUN yarn
RUN yarn build

# production stage
FROM nginx:1.17-alpine as production-stage
COPY --from=build-stage /app/apps/standalone/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
