import { FormLayout, Stack, Text } from "@shopify/polaris";
import { memo, useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import Form from "src/components/Form";
import FormItem from "src/components/Form/Item";
import InputOTP from "src/modules/setting/component/Security/InputOTP/InputOTP";
import { object, string } from "yup";
interface ExternalAuth {
  initialValues?: {
    twoFactorEnabled: boolean;
    twoFactorMethod: string;
  };
  props: {
    method: string;
    key: string;
  };
  setDataSubmitExternalAuth: (value: any) => void;
  errorMessage?: string;
  setErrorMessage: (value: string | undefined) => void;
}
const ExternalAuth = ({
  initialValues,
  props,
  setDataSubmitExternalAuth,
  errorMessage,
  setErrorMessage,
}: ExternalAuth) => {
  const [value, setValue] = useState<any>();
  const handleChange = useCallback((value: string) => {
    setValue(value);
  }, []);
  const handleChangeValueForm = useCallback((value: any) => {
    handleChange(value.code);
  }, []);
  const validateObject = object().shape({
    code: string().required("OTP is required"),
  });
  const handleSubmit = useCallback(
    (data: any) => {
      setDataSubmitExternalAuth({
        method: initialValues?.twoFactorMethod,
        ...data,
      });
    },
    [initialValues]
  );
  const { t, i18n } = useTranslation();

  useEffect(() => {
    setDataSubmitExternalAuth && setDataSubmitExternalAuth(value);
  }, [value]);
  return (
    <Form
      initialValues={{ code: "" }}
      validationSchema={validateObject}
      onSubmit={() => {}}
      onValuesChange={handleChangeValueForm}
    >
      <div className="main-content">
        <FormLayout>
          <Stack vertical>
            <Text variant="bodyMd" as="p">
              1. Download and install any authenticator application in your
              mobile device (Google Authenticator, 2FAs, Duo Mobile,...etc)
            </Text>
            <div>
              <Text variant="bodyMd" as="span">
                2. Open your authenticator and scan this QR code.
              </Text>
              <div className="">
                <img
                  width={220}
                  height={220}
                  src={`data:image/png;base64,${props.key}`}
                />
              </div>
            </div>
            <div>
              <div className="mb-2">
                <Text variant="bodyMd" as="span">
                  3. Enter the OTP generated by the authenticator application.
                </Text>
              </div>
              <FormItem name="code">
                <InputOTP
                  errorMessage={errorMessage}
                  setErrorMessage={setErrorMessage}
                />
              </FormItem>
            </div>
          </Stack>
        </FormLayout>
      </div>
    </Form>
  );
};
export default memo(ExternalAuth);
