export enum ACTIVATE_TYPE {
  NEW_TICKET_BY_AGENT = "NEW_TICKET_BY_AGENT",
  NEW_TICKET_BY_CUSTOMER = "NEW_TICKET_BY_CUSTOMER",
  NEW_REPLY_BY_AGENT = "NEW_REPLY_BY_AGENT",
  NEW_REPLY_BY_CUSTOMER = "NEW_REPLY_BY_CUSTOMER",
}
