export const QUERY_KEY = {
  GLOBAL: "global",
  SUMMARY: "reportSummary",
  LIST_TICKET_CUSTOMER: "listTicketCustomer",
  LIST_CUSTOMER: "listCustomer",
  REPORT_SUPPORT_VOLUME: "reportSupportVolume",
  REPORT_RESOLUTION_TIME: "reportResolutionTime",
  REPORT_FIRST_RESPONSE_TIME: "reportFirstResponseTime",
  REPORT_BY_TAGS: "reportByTags",
  REPORT_TOP_FIVE: "reportTopFive",
  LIST_AGENT: "listAgent",
  LIST_CUSTOMER_SHOPIFY: "listCustomerShopify",
  CUSTOMER_SHOPIFY: "customerShopify",
  CUSTOMER_SHOPIFY_ORDER: "customerShopifyOrder",
  BUSINESS_HOURS: "businessHour",
};
