# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "MooseDesk Local"
client_id = "6beffae9e7e2d336d04c001812119383"
application_url = "https://9c11-113-22-84-217.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_customers,read_orders"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://9c11-113-22-84-217.ngrok-free.app/auth/callback",
  "https://9c11-113-22-84-217.ngrok-free.app/auth/shopify/callback",
  "https://9c11-113-22-84-217.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "md-dev-vuong-01.myshopify.com"
