# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "nam999"
client_id = "1daf15909ca639111b7358c7c37e6660"
application_url = "https://tennessee-study-rapid-hostel.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://tennessee-study-rapid-hostel.trycloudflare.com/auth/callback",
  "https://tennessee-study-rapid-hostel.trycloudflare.com/auth/shopify/callback",
  "https://tennessee-study-rapid-hostel.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nam999.myshopify.com"
