# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "MooseDesk Local"
client_id = "6beffae9e7e2d336d04c001812119383"
application_url = "https://spoke-franklin-aluminium-sort.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://spoke-franklin-aluminium-sort.trycloudflare.com/auth/callback",
  "https://spoke-franklin-aluminium-sort.trycloudflare.com/auth/shopify/callback",
  "https://spoke-franklin-aluminium-sort.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "md-dev-vuong-01.myshopify.com"
