# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "MooseDesk Dev"
client_id = "a676c7a70cdd88e08ff89355e51d357f"
application_url = "https://app-shopify-dev.moosedesk.net"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_customers,read_orders"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://app-shopify-dev.moosedesk.net/auth/callback",
  "https://app-shopify-dev.moosedesk.net/auth/shopify/callback",
  "https://app-shopify-dev.moosedesk.net/api/auth/callback"
]

[webhooks]
api_version = "2022-10"

[pos]
embedded = false
