# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "MooseDesk Ecommerce Help Desk"
client_id = "d2676c33fa9d7ec9e2284b03d6a4d0bb"
application_url = "https://app.moosedesk.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://app.moosedesk.com/auth/callback",
  "https://app.moosedesk.com/auth/shopify/callback",
  "https://app.moosedesk.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://app.moosedesk.com/webhooks/customers/redact"
  customer_data_request_url = "https://app.moosedesk.com/webhooks/customers/data_request"
  shop_deletion_url = "https://app.moosedesk.com/webhooks/shop/redact"

[pos]
embedded = false
